name: draw
dependencies:
  - python=3.8.5
  - pip:
    - numpy==1.19.3
    # numpy 1.19.4 has a bug
    # https://github.com/numpy/numpy/wiki/FMod-Bug-on-Windows
    - opencv-contrib-python
    - pyinstaller
    - Pillow
